version: '3'
services:
  db:
    image: mysql:latest
    container_name: local-forum-app-db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: forum_app
    volumes:
      - /home/overhaul/Documents/learn/local_db:/var/lib/mysql